name: basic CI/CD

on:
  push:
    branches:
      - refactor
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install SSH agent and add deploy key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 3. Deploy to remote Windows server
      - name: Deploy to Windows server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            cd C:/Gole-Certo;
            git pull origin main;
            docker compose down;
            docker compose up -d --build
          "
